# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradPlusAdSDK', '11.4.0'
  pod 'Ads-Fusion-CN-Beta/BUAdSDK', '6.1.1.0'
  pod 'Ads-Fusion-CN-Beta/CSJMediation', '6.1.1.0'

end
